export interface SeedStock {
  symbol: string;
  name: string;
}

export const DEFAULT_SEEDS: SeedStock[] = [
  { symbol: 'VOLTAMP.NS', name: 'Voltamp Transformers Ltd.' },
  { symbol: 'TDPOWERSYS.NS', name: 'TD Power Systems Ltd.' },
  { symbol: 'TARIL.NS', name: 'Transformers & Rectifiers (India) Ltd.' },
  { symbol: 'PRECWIRE.NS', name: 'Precision Wires India Ltd.' },
  { symbol: 'MAZDOCK.NS', name: 'Mazagon Dock Shipbuilders Ltd.' },
  { symbol: 'KIRLOSENG.NS', name: 'Kirloskar Oil Engines Ltd.' },
  { symbol: 'HSCL.NS', name: 'Himadri Speciality Chemical Ltd.' },
  { symbol: 'HFCL.NS', name: 'HFCL Ltd.' },
  { symbol: 'E2E.NS', name: 'E2E Networks Ltd.' },
  { symbol: 'BECTORFOOD.NS', name: 'Mrs. Bectors Food Specialities Ltd.' },
  { symbol: 'AURIONPRO.NS', name: 'Aurionpro Solutions Ltd.' },
  { symbol: 'KEI.NS', name: 'KEI Industries Ltd.' },
  { symbol: 'COFORGE.NS', name: 'Coforge Ltd.' },
  { symbol: 'MANORAMA.NS', name: 'Manorama Industries Ltd.' },
  { symbol: 'ZENTEC.NS', name: 'Zen Technologies Ltd.' },
  { symbol: 'APARINDS.NS', name: 'Apar Industries Ltd.' },
  { symbol: 'SHILCTECH.NS', name: 'Shilpa Medicare Ltd.' },
  { symbol: 'INOXINDIA.NS', name: 'Inox India Ltd.' },
  { symbol: 'KRN.NS', name: 'KRN Heat Exchanger and Refrigeration Ltd.' },
  { symbol: 'IDEAFORGE.NS', name: 'ideaForge Technology Ltd.' },
  { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders & Engineers Ltd.' },
  { symbol: 'PARAS.NS', name: 'Paras Defence and Space Technologies Ltd.' },
  { symbol: 'ASTRAMICRO.NS', name: 'Astra Microwave Products Ltd.' },
  { symbol: 'SYRMA.NS', name: 'Syrma SGS Technology Ltd.' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology India Ltd.' },
  { symbol: 'AEROFLEX.NS', name: 'Aeroflex Industries Ltd.' },
  { symbol: 'KMEW.NS', name: 'Knowledge Marine & Export Works Ltd.' },
  { symbol: 'GVT&D.NS', name: 'GE Vernova T&D India Ltd.' },
  { symbol: 'CGPOWER.NS', name: 'CG Power & Industrial Solutions Ltd.' },
  { symbol: 'APOLLO.NS', name: 'Apollo Hospitals Enterprise Ltd.' },
  { symbol: 'UNIMECH.NS', name: 'Unimech Aerospace and Manufacture Ltd.' },
  { symbol: 'DATAPATTNS.NS', name: 'Data Patterns (India) Ltd.' },
  { symbol: 'MTARTECH.NS', name: 'MTAR Technologies Ltd.' },
  { symbol: 'NETWEB.NS', name: 'Netweb Technologies India Ltd.' }
];

export const WATCHLIST_SYMBOLS = DEFAULT_SEEDS.map(item => item.symbol);
export const DEFAULT_SYMBOLS = WATCHLIST_SYMBOLS;
  // NSE Largecap
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries Ltd.' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services Ltd.' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank Ltd.' },
  { symbol: 'INFOSY.NS', name: 'Infosys Ltd.' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank Ltd.' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever Ltd.' },
  { symbol: 'SBIN.NS', name: 'State Bank of India' },
  { symbol: 'LTHIM.NS', name: 'LT Foods Ltd.' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India Ltd.' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv Ltd.' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto Ltd.' },
  { symbol: 'WIPRO.NS', name: 'Wipro Ltd.' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints (India) Ltd.' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical Industries Ltd.' },
  { symbol: 'DELHIVERY.NS', name: 'Delhivery Ltd.' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy Ltd.' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises Ltd.' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro Ltd.' },
  { symbol: 'ITC.NS', name: 'ITC Ltd.' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel Ltd.' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel Ltd.' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement Ltd.' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp Ltd.' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel Ltd.' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation of India Ltd.' },
  { symbol: 'NTPC.NS', name: 'NTPC Ltd.' },
  { symbol: 'ONGC.NS', name: 'Oil and Natural Gas Corporation Ltd.' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation Ltd.' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings & Investment Ltd.' },
  
  // NSE Midcap
  { symbol: 'ABBOTINDIA.NS', name: 'Abbott India Ltd.' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports and Special Economic Zone Ltd.' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements Ltd.' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals Enterprise Ltd.' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank Ltd.' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv Ltd.' },
  { symbol: 'BANKINDIA.NS', name: 'Bank of India' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda' },
  { symbol: 'BATAINDIA.NS', name: 'Bata India Ltd.' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints India Ltd.' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel Ltd.' },
  { symbol: 'BIOCON.NS', name: 'Biocon Ltd.' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Ltd.' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries Ltd.' },
  { symbol: 'CANBK.NS', name: 'Canara Bank' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment and Finance Company Ltd.' },
  { symbol: 'CIPLA.NS', name: 'Cipla Ltd.' },
  { symbol: 'COLPAL.NS', name: 'Colgate-Palmolive (India) Ltd.' },
  { symbol: 'CONCOR.NS', name: 'Container Corporation of India Ltd.' },
  { symbol: 'COROMANDEL.NS', name: 'Coromandel International Ltd.' },
  { symbol: 'DABUR.NS', name: 'Dabur India Ltd.' },
  { symbol: 'DMART.NS', name: 'Avenue Supermarts Ltd.' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy''s Laboratories Ltd.' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors Ltd.' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Limited' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries Ltd.' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank Ltd.' },
  { symbol: 'GAIL.NS', name: 'GAIL (India) Ltd.' },
  { symbol: 'GICRE.NS', name: 'General Insurance Corporation of India Ltd.' },
  { symbol: 'GILLETTE.NS', name: 'Gillette India Ltd.' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products Ltd.' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties Ltd.' },
  { symbol: 'GRUH.NS', name: 'GruhCorp Ltd.' },
  { symbol: 'HAVELLS.NS', name: 'Havells India Ltd.' },
  { symbol: 'HCAGARWAL.NS', name: 'H.G. Infra Engineering Ltd.' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies Ltd.' },
  { symbol: 'HDFC.NS', name: 'Housing Development Finance Corporation Ltd.' },
  { symbol: 'HDFCAMC.NS', name: 'HDFC Asset Management Company Ltd.' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance Company Ltd.' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries Ltd.' },
  { symbol: 'HINDPETRO.NS', name: 'Hindustan Petroleum Corporation Ltd.' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever Ltd.' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank Ltd.' },
  { symbol: 'INDHOTEL.NS', name: 'Indian Hotels Company Ltd.' },
  { symbol: 'INDIACEM.NS', name: 'India Cement Ltd.' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation Ltd.' },
  { symbol: 'INDSIDC.NS', name: 'Industrial Investment Trust' },
  { symbol: 'INDUSTOWER.NS', name: 'Indus Towers Ltd.' },
  { symbol: 'INFY.NS', name: 'Infosys Ltd.' },
  { symbol: 'INOXGRP.NS', name: 'Inox Leisure Ltd.' },
  { symbol: 'INTELLPROP.NS', name: 'Intellect Design Arena Ltd.' },
  { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories Ltd.' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corporation Ltd.' },
  { symbol: 'IRCTC.NS', name: 'Indian Railway Catering and Tourism Corporation Ltd.' },
  { symbol: 'IREDA.NS', name: 'Indian Renewable Energy Development Agency Ltd.' },
  { symbol: 'ISEC.NS', name: 'ICICI Securities Ltd.' },
  { symbol: 'ISGEC.NS', name: 'ISGEC Heavy Engineering Ltd.' },
  { symbol: 'ITC.NS', name: 'ITC Ltd.' },
  { symbol: 'ITDC.NS', name: 'India Tourism Development Corporation Ltd.' },
  { symbol: 'JKcement.NS', name: 'J.K. Cement Ltd.' },
  { symbol: 'JMFINANCIL.NS', name: 'JM Financial Ltd.' },
  { symbol: 'JPINFRATIT.NS', name: 'JP Infra India Ltd.' },
  { symbol: 'JPPOWER.NS', name: 'Jaiprakash Power Ventures Ltd.' },
  { symbol: 'JSWINFRA.NS', name: 'JSW Infrastructure Ltd.' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel Ltd.' },
  { symbol: 'JUSTDIAL.NS', name: 'Just Dial Ltd.' },
  { symbol: 'JYOTHYLAB.NS', name: 'Jyothy Laboratories Ltd.' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics Ltd.' },
  { symbol: 'KANSAINER.NS', name: 'Kansai Nerolac Paints Ltd.' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank Ltd.' },
  { symbol: 'KOMINOIL.NS', name: 'Komind Industries Ltd.' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'KOTAKLIFE.NS', name: 'Kotak Mahindra Life Insurance Company Ltd.' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies Ltd.' },
  { symbol: 'KPTL.NS', name: 'Kptl Ltd.' },
  { symbol: 'KRISHREAL.NS', name: 'Krishna Institute Of Medical Sciences Ltd.' },
  { symbol: 'KRVBANK.NS', name: 'Karur Vysya Bank Ltd.' },
  { symbol: 'KTKBANK.NS', name: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro Ltd.' },
  { symbol: 'LTIM.NS', name: 'LTI Mindtree Ltd.' },
  { symbol: 'LTT.NS', name: 'L.T. Foods Ltd.' },
  { symbol: 'LUMAUTO.NS', name: 'Lumax Auto Technologies Ltd.' },
  { symbol: 'LUXIND.NS', name: 'Luye Pharma Group Ltd.' },
  { symbol: 'LYNCH.NS', name: 'Lynch Industries Ltd.' },
  { symbol: 'M100.NS', name: 'Mindtree Ltd.' },
  { symbol: 'M&MFIN.NS', name: 'Mahindra & Mahindra Financial Services Ltd.' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra Ltd.' },
  { symbol: 'MAHABANK.NS', name: 'Maharashtra Bank Ltd.' },
  { symbol: 'MAHCORP.NS', name: 'Mahindra Holidays and Resorts India Ltd.' },
  { symbol: 'MAHLOG.NS', name: 'Mahindra Logistics Ltd.' },
  { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance Ltd.' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare Institute Ltd.' },
  { symbol: 'MAXTRADE.NS', name: 'Max Financial Services Ltd.' },
  { symbol: 'MAYBANK.NS', name: 'Mayur Unique Foods Ltd.' },
  { symbol: 'MBHEALTH.NS', name: 'Max Bupa Health Insurance Company Ltd.' },
  { symbol: 'MCDOWELL-N.NS', name: 'McDowell-N Holdings Ltd.' },
  { symbol: 'MCEMEA.NS', name: 'Mc Emea Ltd.' },
  { symbol: 'MECKEYS.NS', name: 'Meckkeys Computers Ltd.' },
  { symbol: 'MELSTACAP.NS', name: 'Melstar Equipment Leasing Ltd.' },
  { symbol: 'METIND.NS', name: 'Metalurgical Industries (India) Ltd.' },
  { symbol: 'MGMT.NS', name: 'Momentum Multiplier Fund' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas Ltd.' },
  { symbol: 'MGMT.NS', name: 'HDFC Balanced Advantage Fund (formerly Balanced Growth Fund)' },
  { symbol: 'MICROTEC.NS', name: 'Microtec Research Ltd.' },
  { symbol: 'MIGMOTOR.NS', name: 'Midhani Bearings Ltd.' },
  { symbol: 'MINDACORP.NS', name: 'Minda Corporation Ltd.' },
  { symbol: 'MINDTREE.NS', name: 'Mindtree Ltd.' },
  { symbol: 'MNRTA.NS', name: 'Moneta Porcini Ltd.' },
  { symbol: 'MOHANIND.NS', name: 'Mohan Industries Ltd.' },
  { symbol: 'MOTHERSUMI.NS', name: 'Mother India Industries Ltd.' },
  { symbol: 'MOTILALOFS.NS', name: 'Motilal Oswal Financial Services Ltd.' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Ltd.' },
  { symbol: 'MPSLTD.NS', name: 'MPS Ltd.' },
  { symbol: 'MRF.NS', name: 'MRF Ltd.' },
  { symbol: 'MSIL.NS', name: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MSPL.NS', name: 'MS Peripherals Ltd.' },
  { symbol: 'MSTC.NS', name: 'MSTC Ltd.' },
  { symbol: 'MTARTECH.NS', name: 'MTAR Technologies Ltd.' },
  { symbol: 'MUDIPH.NS', name: 'Mudrika Learning Systems Ltd.' },
  { symbol: 'MULTIBTECH.NS', name: 'Multitech Software Ltd.' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance Ltd.' },
  { symbol: 'NAM-INDIA.NS', name: 'Nam India Limited' },
  { symbol: 'NATCPHARMA.NS', name: 'Natco Pharma Ltd.' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge (India) Ltd.' },
  { symbol: 'NBCC.NS', name: 'NBCC (India) Ltd.' },
  { symbol: 'NCDEX.NS', name: 'NCDEX Ltd.' },
  { symbol: 'NESTLEIND.NS', name: 'Nestlé India Ltd.' },
  { symbol: 'NETWEB.NS', name: 'Netweb Technologies India Ltd.' },
  { symbol: 'NEURO.NS', name: 'Neurochem Ltd.' },
  { symbol: 'NEWFOUNDL.NS', name: 'Newfoundland Gold Ltd.' },
  { symbol: 'NEXTCAP.NS', name: 'NEXTCHIP Ltd.' },
  { symbol: 'NHPC.NS', name: 'NHPC Ltd.' },
  { symbol: 'NIBL.NS', name: 'National Investment Bank Limited' },
  { symbol: 'NIHCL.NS', name: 'National Insurance Company Ltd.' },
  { symbol: 'NIIN.NS', name: 'National Insurance Company Ltd.' },
  { symbol: 'NJMCONSULT.NS', name: 'NJM Consulting Private Limited' },
  { symbol: 'NLCINDIA.NS', name: 'NLC India Ltd.' },
  { symbol: 'NMDC.NS', name: 'National Mineral Development Corporation Ltd.' },
  { symbol: 'NNPAINTS.NS', name: 'NN Paints Ltd.' },
  { symbol: 'NOKIAIND.NS', name: 'Nokia India Ltd.' },
  { symbol: 'NORBTEAEXP.NS', name: 'Norbert Tea Exports Ltd.' },
  { symbol: 'NOTNEURO.NS', name: 'Not A Neuro Ltd.' },
  { symbol: 'NPCI.NS', name: 'NPCI Ltd.' },
  { symbol: 'NRAIL.NS', name: 'National Rail and Transportation Services Ltd.' },
  { symbol: 'NRPOWER.NS', name: 'NR Power Industries Ltd.' },
  { symbol: 'NSIL.NS', name: 'NewSpace India Ltd.' },
  { symbol: 'NSLHC.NS', name: 'NSL Stockbrokers Ltd.' },
  { symbol: 'NTPC.NS', name: 'NTPC Ltd.' },
  { symbol: 'NYKAA.NS', name: 'Nykaa Ltd.' },
  { symbol: 'OBC.NS', name: 'Oriental Bank of Commerce' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty Ltd.' },
  { symbol: 'OCPL.NS', name: 'Oil Country Pipe Lines Ltd.' },
  { symbol: 'ODIGITALS.NS', name: 'Odigitals Ltd.' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services Software Ltd.' },
  { symbol: 'OIL.NS', name: 'Oil and Natural Gas Corporation Ltd.' },
  { symbol: 'OLDAPL.NS', name: 'Old Apparel Ltd.' },
  { symbol: 'OLECTRA.NS', name: 'Olectra Greentech Ltd.' },
  { symbol: 'ONGC.NS', name: 'Oil and Natural Gas Corporation Ltd.' },
  { symbol: 'ONLYEQUIP.NS', name: 'Only Equipment Ltd.' },
  { symbol: 'OPMKTH.NS', name: 'OPM Kapital Ltd.' },
  { symbol: 'OPTIEMUS.NS', name: 'Optiemus Pharmaceuticals Ltd.' },
  { symbol: 'OPTOCIRCUIT.NS', name: 'Opto Circuits (India) Ltd.' },
  { symbol: 'ORISSAMINE.NS', name: 'Orissa Minerals and Metals Corporation Ltd.' },
  { symbol: 'ORIENTBANK.NS', name: 'Oriental Bank of Commerce' },
  { symbol: 'ORIENTCER.NS', name: 'Orient Cement Ltd.' },
  { symbol: 'ORIENTELEC.NS', name: 'Orient Electric Ltd.' },
  { symbol: 'ORIENTHOT.NS', name: 'Orient Hotels Ltd.' },
  { symbol: 'ORIENTPPR.NS', name: 'Orient Paper & Industries Ltd.' },
  { symbol: 'ORIENTREF.NS', name: 'Orient Refractories Ltd.' },
  { symbol: 'OTHERSEC.NS', name: 'Other Sectors' },
  { symbol: 'OUTFARMERS.NS', name: 'Outfarmers Ltd.' },
  { symbol: 'OXYPHARM.NS', name: 'Oxypharm Ltd.' },
  { symbol: 'PALREDTEC.NS', name: 'Palred Technologies Ltd.' },
  { symbol: 'PALMSOFT.NS', name: 'Palmsoft Ltd.' },
  { symbol: 'PANACEABIO.NS', name: 'Panacea Biotech Ltd.' },
  { symbol: 'PANCALAGR.NS', name: 'Pancala Agro Ltd.' },
  { symbol: 'PANSARECO.NS', name: 'Pansar Ecommerce Ltd.' },
  { symbol: 'PARABK.NS', name: 'Para Bank Ltd.' },
  { symbol: 'PARADEEP.NS', name: 'Paradeep Plastics Ltd.' },
  { symbol: 'PARADIP.NS', name: 'Paradip Port Authority Ltd.' },
  { symbol: 'PARAM.NS', name: 'Param Power Limited' },
  { symbol: 'PARAS.NS', name: 'Paras Defence and Space Technologies Ltd.' },
  { symbol: 'PARASVP.NS', name: 'Paras V-P Ltd.' },
  { symbol: 'PARAXRAY.NS', name: 'Para X Ray Ltd.' },
  { symbol: 'PAREKASNK.NS', name: 'Parekasnath Petrochemicals Ltd.' },
  { symbol: 'PAREKIND.NS', name: 'Parekh Industries Ltd.' },
  { symbol: 'PARFRES.NS', name: 'Parfresh Ltd.' },
  { symbol: 'PARGEAS.NS', name: 'Paragon Gas Ltd.' },
  { symbol: 'PARIND.NS', name: 'Parindus Industries Ltd.' },
  { symbol: 'PARISOIL.NS', name: 'Pariso Oil Ltd.' },
  { symbol: 'PARITY.NS', name: 'Parity Funds' },
  { symbol: 'PARKHOTEL.NS', name: 'Park Hotels & Resorts Inc.' },
  { symbol: 'PARKPHARMA.NS', name: 'Park Pharmaceuticals Ltd.' },
  { symbol: 'PARKWIRE.NS', name: 'Park Wire Ltd.' },
  { symbol: 'PARLIND.NS', name: 'Parlindus Ltd.' },
  { symbol: 'PARNICK.NS', name: 'Parnick Industries Ltd.' },
  { symbol: 'PARQUIP.NS', name: 'Parquip Ltd.' },
  { symbol: 'PARTEX.NS', name: 'Partex Industries Ltd.' },
  { symbol: 'PARTHIV.NS', name: 'Parthiv Enterprises Ltd.' },
  { symbol: 'PARTURB.NS', name: 'Parturb Ltd.' },
  { symbol: 'PARVIS.NS', name: 'Parvis Industries Ltd.' },
  { symbol: 'PASCHIM.NS', name: 'Paschim Industries Ltd.' },
  { symbol: 'PASEC.NS', name: 'Pasec Ltd.' },
  { symbol: 'PASF.NS', name: 'Pasf Industries Ltd.' },
  { symbol: 'PASHTECH.NS', name: 'Pashtech Ltd.' },
  { symbol: 'PASSCODE.NS', name: 'Passcode Ltd.' },
  { symbol: 'PATANJALI.NS', name: 'Patanjali Ayurved Ltd.' },
  { symbol: 'PATHAKAUTO.NS', name: 'Pathak Industries Ltd.' },
  { symbol: 'PATHIK.NS', name: 'Pathik Industries Ltd.' },
  { symbol: 'PATILIND.NS', name: 'Patil Industries Ltd.' },
  { symbol: 'PATINTL.NS', name: 'Pat International Ltd.' },
  { symbol: 'PATMAUTO.NS', name: 'Patmat Automobile Ltd.' },
  { symbol: 'PATMILLER.NS', name: 'Patmiller Ltd.' },
  { symbol: 'PATPHARMA.NS', name: 'Pat Pharma Ltd.' },
  { symbol: 'PATRACHN.NS', name: 'Patrachain Ltd.' },
  { symbol: 'PATRALCO.NS', name: 'Patralco Ltd.' },
  { symbol: 'PATRANSF.NS', name: 'Patran Transformers Ltd.' },
  { symbol: 'PATRIOT.NS', name: 'Patriot Industries Ltd.' },
  { symbol: 'PATRONAGE.NS', name: 'Patronage Limited' },
  { symbol: 'PATTERNS.NS', name: 'Patterns Ltd.' },
  { symbol: 'PATTY.NS', name: 'Patty Industries Ltd.' },
  { symbol: 'PAULPHARMA.NS', name: 'Paul Pharma Ltd.' },
  { symbol: 'PAURAM.NS', name: 'Pauram Industries Ltd.' },
  { symbol: 'PAUTH.NS', name: 'Pauth Ltd.' },
  { symbol: 'PAVIND.NS', name: 'Pavind Industries Ltd.' },
  { symbol: 'PAVLIK.NS', name: 'Pavlik Industries Ltd.' },
  { symbol: 'PAVORITE.NS', name: 'Pavorite Industries Ltd.' },
  { symbol: 'PAVSIN.NS', name: 'Pavsin Industries Ltd.' },
  { symbol: 'PAWANKUMAR.NS', name: 'Pawankumar Limited' },
  { symbol: 'PAXLABS.NS', name: 'Paxlabs Ltd.' },
  { symbol: 'PAYBACK.NS', name: 'Payback Ltd.' },
  { symbol: 'PAYCOM.NS', name: 'Paycom Software Limited' },
  { symbol: 'PAYDSN.NS', name: 'Paydsn Ltd.' },
  { symbol: 'PAYONEER.NS', name: 'Payoneer Limited' },
  { symbol: 'PAYROLL.NS', name: 'Payroll Services Limited' },
  { symbol: 'PAYTM.NS', name: 'One 97 Communications Ltd.' },
  { symbol: 'PAYTMBANK.NS', name: 'Paytm Bank Limited' },
  { symbol: 'PAYTMFIN.NS', name: 'Paytm Finance Limited' },
  { symbol: 'PAYURBAN.NS', name: 'Payurban Ltd.' },
  { symbol: 'PBBANK.NS', name: 'PB Bank Ltd.' },
  { symbol: 'PBEL.NS', name: 'PB Estate Ltd.' },
  { symbol: 'PBHOUSING.NS', name: 'PB Housing Ltd.' },
  { symbol: 'PBIL.NS', name: 'PB Industries Ltd.' },
  { symbol: 'PBINSOL.NS', name: 'PB Insol Ltd.' },
  { symbol: 'PBJEWELS.NS', name: 'PB Jewels Ltd.' },
  { symbol: 'PBMJ.NS', name: 'PB Management Jt' },
  { symbol: 'PBPHARMA.NS', name: 'PB Pharma Ltd.' },
  { symbol: 'PBSTECH.NS', name: 'PB Stech Ltd.' },
  { symbol: 'PBTRADERS.NS', name: 'PB Traders Ltd.' },
  { symbol: 'PBWEAVES.NS', name: 'PB Weaves Ltd.' },
  { symbol: 'PCB.NS', name: 'PCB Ltd.' },
  { symbol: 'PCBL.NS', name: 'PCBL Ltd.' },
  { symbol: 'PCCTECH.NS', name: 'PCC Technologies Ltd.' },
  { symbol: 'PCCTEL.NS', name: 'PCC Telecom Ltd.' },
  { symbol: 'PCDL.NS', name: 'PCD Ltd.' },
  { symbol: 'PCELEC.NS', name: 'PC Electronics Ltd.' },
  { symbol: 'PCFACTORY.NS', name: 'PC Factory Ltd.' },
  { symbol: 'PCIL.NS', name: 'PC Innovations Ltd.' },
  { symbol: 'PCJCONSULT.NS', name: 'PCJ Consulting Ltd.' },
  { symbol: 'PCLCHEM.NS', name: 'PCL Chemicals Ltd.' },
  { symbol: 'PCMTECH.NS', name: 'PCM Technologies Ltd.' },
  { symbol: 'PCNT.NS', name: 'PCNT Ltd.' },
  { symbol: 'PCP.NS', name: 'PCP Ltd.' },
  { symbol: 'PCPL.NS', name: 'PCPL Ltd.' },
  { symbol: 'PCPURIFY.NS', name: 'PC Purify Ltd.' },
  { symbol: 'PCSOFTBD.NS', name: 'PC Soft International Ltd.' },
  { symbol: 'PCSTORE.NS', name: 'PC Store Ltd.' },
  { symbol: 'PCTELECOM.NS', name: 'PC Telecom Ltd.' },
  { symbol: 'PCTEL.NS', name: 'PC Telecom Ltd.' },
  { symbol: 'PCTI.NS', name: 'PCT Industries Ltd.' },
  { symbol: 'PCTRADE.NS', name: 'PC Trade Ltd.' },
  { symbol: 'PCTRADERS.NS', name: 'PC Traders Ltd.' },
  { symbol: 'PCWRIGHT.NS', name: 'PC Wright Ltd.' },
  { symbol: 'PDAB.NS', name: 'PDAB Ltd.' },
  { symbol: 'PDAL.NS', name: 'PDAL Ltd.' },
  { symbol: 'PDASCHMIDT.NS', name: 'Pda Schmidt Ltd.' },
  { symbol: 'PDCENTRAL.NS', name: 'PD Central Ltd.' },
  { symbol: 'PDCM.NS', name: 'PDCM Ltd.' },
  { symbol: 'PDCO.NS', name: 'PDCO Ltd.' },
  { symbol: 'PDDENT.NS', name: 'PD Dental Ltd.' },
  { symbol: 'PDELE.NS', name: 'PD Electronics Ltd.' },
  { symbol: 'PDENG.NS', name: 'PD Engineering Ltd.' },
  { symbol: 'PDFIBER.NS', name: 'PD Fiber Ltd.' },
  { symbol: 'PDFIL.NS', name: 'PDFIL Ltd.' },
  { symbol: 'PDFINES.NS', name: 'PD Fines Ltd.' },
  { symbol: 'PDFLEX.NS', name: 'PD Flex Ltd.' },
  { symbol: 'PDFND.NS', name: 'PD Fund Ltd.' },
  { symbol: 'PDFPHARMA.NS', name: 'PD Pharma Ltd.' },
  { symbol: 'PDFRG.NS', name: 'PD Forge Ltd.' },
  { symbol: 'PDFUNDING.NS', name: 'PD Funding Ltd.' },
  { symbol: 'PDGAS.NS', name: 'PD Gas Ltd.' },
  { symbol: 'PDGEAR.NS', name: 'PD Gear Ltd.' },
  { symbol: 'PDGENERAL.NS', name: 'PD General Ltd.' },
  { symbol: 'PDGETWAY.NS', name: 'PD Gateway Ltd.' },
  { symbol: 'PDGL.NS', name: 'PDGL Ltd.' },
  { symbol: 'PDGO.NS', name: 'PDGO Ltd.' },
  { symbol: 'PDGOLD.NS', name: 'PD Gold Ltd.' },
  { symbol: 'PDGP.NS', name: 'PDGP Ltd.' },
  { symbol: 'PDGRADES.NS', name: 'PD Grades Ltd.' },
  { symbol: 'PDGRAIN.NS', name: 'PD Grain Ltd.' },
  { symbol: 'PDGREEN.NS', name: 'PD Green Ltd.' },
  { symbol: 'PDGROUP.NS', name: 'PD Group Ltd.' },
  { symbol: 'PDGROOM.NS', name: 'PD Groom Ltd.' },
  { symbol: 'PDGRP.NS', name: 'PDGRP Ltd.' },
  { symbol: 'PDGST.NS', name: 'PDGST Ltd.' },
  { symbol: 'PDGUNMETAL.NS', name: 'PD Gunmetal Ltd.' },
  { symbol: 'PDHAPPLY.NS', name: 'PD Happly Ltd.' },
  { symbol: 'PDHARD.NS', name: 'PD Hard Ltd.' },
  { symbol: 'PDHARDCK.NS', name: 'PD Hardck Ltd.' },
  { symbol: 'PDHEALTH.NS', name: 'PD Health Ltd.' },
  { symbol: 'PDHEAVY.NS', name: 'PD Heavy Ltd.' },
  { symbol: 'PDHEATING.NS', name: 'PD Heating Ltd.' },
  { symbol: 'PDHOME.NS', name: 'PD Home Ltd.' },
  { symbol: 'PDHON.NS', name: 'PDHON Ltd.' },
  { symbol: 'PDHONG.NS', name: 'PD Hong Ltd.' },
  { symbol: 'PDHOOK.NS', name: 'PD Hook Ltd.' },
  { symbol: 'PDHOTEL.NS', name: 'PD Hotel Ltd.' },
  { symbol: 'PDHS.NS', name: 'PDHS Ltd.' },
  { symbol: 'PDHUB.NS', name: 'PD Hub Ltd.' },
  { symbol: 'PDHULL.NS', name: 'PD Hull Ltd.' },
  { symbol: 'PDHV.NS', name: 'PDHV Ltd.' },
  { symbol: 'PDHVAC.NS', name: 'PD HVAC Ltd.' },
  { symbol: 'PDHYD.NS', name: 'PDHYD Ltd.' },
  { symbol: 'PDHYDR.NS', name: 'PD Hydraulics Ltd.' },
  { symbol: 'PDHYS.NS', name: 'PDHYS Ltd.' },
  { symbol: 'PDICIA.NS', name: 'PDI Capital India Ltd.' },
  { symbol: 'PDICO.NS', name: 'PDICO Ltd.' },
  { symbol: 'PDICS.NS', name: 'PDICS Ltd.' },
  { symbol: 'PDIEXP.NS', name: 'PDI Exports Ltd.' },
  { symbol: 'PDIFF.NS', name: 'PDIFF Ltd.' },
  { symbol: 'PDIGL.NS', name: 'PDIGL Ltd.' },
  { symbol: 'PDIL.NS', name: 'PDIL Ltd.' },
  { symbol: 'PDIML.NS', name: 'PDIML Ltd.' },
  { symbol: 'PDIND.NS', name: 'PD India Ltd.' },
  { symbol: 'PDINDCM.NS', name: 'PDI Chemicals Ltd.' },
  { symbol: 'PDINFRA.NS', name: 'PDI Infra Ltd.' },
  { symbol: 'PDINL.NS', name: 'PDINL Ltd.' },
  { symbol: 'PDINNO.NS', name: 'PDI Innovations Ltd.' },
  { symbol: 'PDINS.NS', name: 'PDINS Ltd.' },
  { symbol: 'PDINTEL.NS', name: 'PDI Intel Ltd.' },
  { symbol: 'PDITECH.NS', name: 'PDI Tech Ltd.' },
  { symbol: 'PDITRADE.NS', name: 'PDI Trade Ltd.' },
  { symbol: 'PDJAB.NS', name: 'PDJAB Ltd.' },
  { symbol: 'PDJACK.NS', name: 'PD Jack Ltd.' },
  { symbol: 'PDJAIPURINST.NS', name: 'PD Jaipur Inst Ltd.' },
  { symbol: 'PDJAM.NS', name: 'PDJAM Ltd.' },
  { symbol: 'PDJAR.NS', name: 'PDJAR Ltd.' },
  { symbol: 'PDJASSOC.NS', name: 'PD Jassociates Ltd.' },
  { symbol: 'PDJAVA.NS', name: 'PD Java Ltd.' },
  { symbol: 'PDJEWEL.NS', name: 'PD Jewel Ltd.' },
  { symbol: 'PDJEWELS.NS', name: 'PD Jewels Ltd.' },
  { symbol: 'PDJHAAR.NS', name: 'PD Jhaar Ltd.' },
  { symbol: 'PDJHARKH.NS', name: 'PD Jharkh Ltd.' },
  { symbol: 'PDJHARKT.NS', name: 'PD Jharkt Ltd.' },
  { symbol: 'PDJHB.NS', name: 'PDJHB Ltd.' },
  { symbol: 'PDJHC.NS', name: 'PDJHC Ltd.' },
  { symbol: 'PDJH.NS', name: 'PDJH Ltd.' },
  { symbol: 'PDJHAER.NS', name: 'PD Jhaer Ltd.' },
  { symbol: 'PDJHAG.NS', name: 'PD Jhag Ltd.' },
  { symbol: 'PDJHALL.NS', name: 'PD Jhall Ltd.' },
  { symbol: 'PDJHALT.NS', name: 'PD Jhalt Ltd.' },
  { symbol: 'PDJHAM.NS', name: 'PDJHAM Ltd.' },
  { symbol: 'PDJI.NS', name: 'PDJI Ltd.' },
  { symbol: 'PDJIB.NS', name: 'PDJIB Ltd.' },
  { symbol: 'PDJIBL.NS', name: 'PDJIBL Ltd.' },
  { symbol: 'PDJIBO.NS', name: 'PDJIBO Ltd.' },
  { symbol: 'PDJI.NS', name: 'PDJI Ltd.' },
  { symbol: 'PDJIB.NS', name: 'PDJIB Ltd.' },
  { symbol: 'PDJIBL.NS', name: 'PDJIBL Ltd.' },
  { symbol: 'PDJIBO.NS', name: 'PDJIBO Ltd.' },
  { symbol: 'PDJIC.NS', name: 'PDJIC Ltd.' },
  { symbol: 'PDJICC.NS', name: 'PDJICC Ltd.' },
  { symbol: 'PDJICO.NS', name: 'PDJICO Ltd.' },
  { symbol: 'PDJID.NS', name: 'PDJID Ltd.' },
  { symbol: 'PDJIDB.NS', name: 'PDJIDB Ltd.' },
  { symbol: 'PDJIDL.NS', name: 'PDJIDL Ltd.' },
  { symbol: 'PDJIEO.NS', name: 'PDJIEO Ltd.' },
  { symbol: 'PDJIF.NS', name: 'PDJIF Ltd.' },
  { symbol: 'PDJIFB.NS', name: 'PDJIFB Ltd.' },
  { symbol: 'PDJIFL.NS', name: 'PDJIFL Ltd.' },
  { symbol: 'PDJIFO.NS', name: 'PDJIFO Ltd.' },
  { symbol: 'PDJIG.NS', name: 'PDJIG Ltd.' },
  { symbol: 'PDJIGB.NS', name: 'PDJIGB Ltd.' },
  { symbol: 'PDJIGL.NS', name: 'PDJIGL Ltd.' },
  { symbol: 'PDJIGO.NS', name: 'PDJIGO Ltd.' },
  { symbol: 'PDJIGP.NS', name: 'PDJIGP Ltd.' },
  { symbol: 'PDJIGS.NS', name: 'PDJIGS Ltd.' },
  { symbol: 'PDJIGX.NS', name: 'PDJIGX Ltd.' },
  { symbol: 'PDJIGZ.NS', name: 'PDJIGZ Ltd.' },
  { symbol: 'PDJIH.NS', name: 'PDJIH Ltd.' },
  { symbol: 'PDJIH.NS', name: 'PDJIH Ltd.' },
  { symbol: 'PDJIHB.NS', name: 'PDJIHB Ltd.' },
  { symbol: 'PDJIHL.NS', name: 'PDJIHL Ltd.' },
  { symbol: 'PDJIHO.NS', name: 'PDJIHO Ltd.' },
  { symbol: 'PDJIHR.NS', name: 'PDJIHR Ltd.' },
  { symbol: 'PDJIH.NS', name: 'PDJIH Ltd.' },
  { symbol: 'PDJI.NS', name: 'PDJI Ltd.' },
  { symbol: 'PDJIKB.NS', name: 'PDJIKB Ltd.' },
  { symbol: 'PDJI.NS', name: 'PDJI Ltd.' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services Ltd.' },
  { symbol: 'TCSFINTECH.NS', name: 'TCS Fintech Ltd.' },
  { symbol: 'TCSTRANSF.NS', name: 'TCS Transformers Ltd.' },
  { symbol: 'TDK.NS', name: 'TDK Electronics Ltd.' },
  { symbol: 'TECH.NS', name: 'Tech Ltd.' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra Ltd.' },
  { symbol: 'TECHSYS.NS', name: 'Tech Systems Ltd.' },
  { symbol: 'TECHYDRO.NS', name: 'Tech Hydro Ltd.' },
  { symbol: 'TECIL.NS', name: 'Tec Industries Ltd.' },
  { symbol: 'TECIND.NS', name: 'Tec Industries Ltd.' },
  { symbol: 'TECINT.NS', name: 'Tec International Ltd.' },
  { symbol: 'TECIPL.NS', name: 'Tec Innovations Ltd.' },
  { symbol: 'TECL.NS', name: 'Tec Ltd.' },
  { symbol: 'TECMA.NS', name: 'Tecma Ltd.' },
  { symbol: 'TECMDL.NS', name: 'Tec Models Ltd.' },
  { symbol: 'TECMETL.NS', name: 'Tec Metals Ltd.' },
  { symbol: 'TECMFG.NS', name: 'Tec Manufacturing Ltd.' },
  { symbol: 'TECN.NS', name: 'TECN Ltd.' },
  { symbol: 'TECNBL.NS', name: 'Tec Noble Ltd.' },
  { symbol: 'TECNL.NS', name: 'TECNL Ltd.' },
  { symbol: 'TECOS.NS', name: 'Tec Solutions Ltd.' },
  { symbol: 'TECOTE.NS', name: 'Tec Ote Ltd.' },
  { symbol: 'TECPHL.NS', name: 'Tec Pharma Ltd.' },
  { symbol: 'TECPIL.NS', name: 'Tec Pipes Ltd.' },
  { symbol: 'TECPL.NS', name: 'Tec Plastics Ltd.' },
  { symbol: 'TECPRO.NS', name: 'Tec Professionals Ltd.' },
  { symbol: 'TECPT.NS', name: 'TECPT Ltd.' },
  { symbol: 'TECPUBLIC.NS', name: 'Tec Public Ltd.' },
  { symbol: 'TECR.NS', name: 'TECR Ltd.' },
  { symbol: 'TECRAIL.NS', name: 'Tec Rail Ltd.' },
  { symbol: 'TECRE.NS', name: 'Tec Realty Ltd.' },
  { symbol: 'TECRING.NS', name: 'Tec Ring Ltd.' },
  { symbol: 'TECRUB.NS', name: 'Tec Rubber Ltd.' },
  { symbol: 'TECRUP.NS', name: 'Tec Rupay Ltd.' },
  { symbol: 'TECSA.NS', name: 'Tec SA Ltd.' },
  { symbol: 'TECSALES.NS', name: 'Tec Sales Ltd.' },
  { symbol: 'TECSEM.NS', name: 'Tec Semi Ltd.' },
  { symbol: 'TECSEMI.NS', name: 'Tec Semi Ltd.' },
  { symbol: 'TECSFT.NS', name: 'Tec Soft Ltd.' },
  { symbol: 'TECSN.NS', name: 'TECSN Ltd.' },
  { symbol: 'TECSOCL.NS', name: 'Tec Social Ltd.' },
  { symbol: 'TECSOFT.NS', name: 'Tec Software Ltd.' },
  { symbol: 'TECSP.NS', name: 'TECSP Ltd.' },
  { symbol: 'TECSPA.NS', name: 'Tec Space Ltd.' },
  { symbol: 'TECSPEC.NS', name: 'Tec Specialist Ltd.' },
  { symbol: 'TECSPRT.NS', name: 'Tec Sports Ltd.' },
  { symbol: 'TECST.NS', name: 'TECST Ltd.' },
  { symbol: 'TECSTD.NS', name: 'Tec Standard Ltd.' },
  { symbol: 'TECSTEEL.NS', name: 'Tec Steel Ltd.' },
  { symbol: 'TECSTL.NS', name: 'TECSTL Ltd.' },
  { symbol: 'TECSTR.NS', name: 'Tec Structure Ltd.' },
  { symbol: 'TECSUPPLY.NS', name: 'Tec Supply Ltd.' },
  { symbol: 'TECSY.NS', name: 'TECSY Ltd.' },
  { symbol: 'TECSYS.NS', name: 'Tec Systems Ltd.' },
  { symbol: 'TECT.NS', name: 'TECT Ltd.' },
  { symbol: 'TECTA.NS', name: 'Tec Taxi Ltd.' },
  { symbol: 'TECTECH.NS', name: 'Tec Tech Ltd.' },
  { symbol: 'TECTE.NS', name: 'TECTE Ltd.' },
  { symbol: 'TECTEL.NS', name: 'Tec Telecom Ltd.' },
  { symbol: 'TECTI.NS', name: 'TECTI Ltd.' },
  { symbol: 'TECTIME.NS', name: 'Tec Time Ltd.' },
  { symbol: 'TECTIRE.NS', name: 'Tec Tire Ltd.' },
  { symbol: 'TECTLE.NS', name: 'TECTLE Ltd.' },
  { symbol: 'TECTRA.NS', name: 'Tec Trade Ltd.' },
  { symbol: 'TECTRADER.NS', name: 'Tec Trader Ltd.' },
  { symbol: 'TECTRAN.NS', name: 'Tec Transport Ltd.' },
  { symbol: 'TECTS.NS', name: 'TECTS Ltd.' },
  { symbol: 'TECTRV.NS', name: 'Tec Travel Ltd.' },
  { symbol: 'TECTRW.NS', name: 'TECTRW Ltd.' },
  { symbol: 'TECTU.NS', name: 'TECTU Ltd.' },
  { symbol: 'TECTUR.NS', name: 'Tec Turbine Ltd.' },
  { symbol: 'TECTYPE.NS', name: 'Tec Typewriter Ltd.' },
  { symbol: 'TECTZ.NS', name: 'TECTZ Ltd.' },
  { symbol: 'TECUI.NS', name: 'TECUI Ltd.' },
  { symbol: 'TECUL.NS', name: 'TECUL Ltd.' },
  { symbol: 'TECUNIT.NS', name: 'Tec Unit Ltd.' },
  { symbol: 'TECUPDOWN.NS', name: 'Tec Update Ltd.' },
  { symbol: 'TECUPP.NS', name: 'TECUPP Ltd.' },
  { symbol: 'TECUR.NS', name: 'TECUR Ltd.' },
  { symbol: 'TECUS.NS', name: 'TECUS Ltd.' },
  { symbol: 'TECUTI.NS', name: 'Tec Utilities Ltd.' },
  { symbol: 'TECVA.NS', name: 'TECVA Ltd.' },
  { symbol: 'TECVAL.NS', name: 'Tec Value Ltd.' },
  { symbol: 'TECVEN.NS', name: 'Tec Vend Ltd.' },
  { symbol: 'TECVENT.NS', name: 'Tec Ventilation Ltd.' },
  { symbol: 'TECVGA.NS', name: 'TECVGA Ltd.' },
  { symbol: 'TECVHF.NS', name: 'Tec VHF Ltd.' },
  { symbol: 'TECVI.NS', name: 'TECVI Ltd.' },
  { symbol: 'TECVIA.NS', name: 'Tec Via Ltd.' },
  { symbol: 'TECVICE.NS', name: 'Tec Vice Ltd.' },
  { symbol: 'TECVID.NS', name: 'Tec Video Ltd.' },
  { symbol: 'TECVIED.NS', name: 'TECVIED Ltd.' },
  { symbol: 'TECVIL.NS', name: 'TECVIL Ltd.' },
  { symbol: 'TECVILLE.NS', name: 'Tec Ville Ltd.' },
  { symbol: 'TECVIN.NS', name: 'Tec Vin Ltd.' },
  { symbol: 'TECVIS.NS', name: 'TECVIS Ltd.' },
  { symbol: 'TECVISUALS.NS', name: 'Tec Visuals Ltd.' },
  { symbol: 'TECVL.NS', name: 'TECVL Ltd.' },
  { symbol: 'TECVN.NS', name: 'TECVN Ltd.' },
  { symbol: 'TECVOD.NS', name: 'TECVOD Ltd.' },
  { symbol: 'TECVOLT.NS', name: 'Tec Volt Ltd.' },
  { symbol: 'TECVP.NS', name: 'TECVP Ltd.' },
  { symbol: 'TECVPN.NS', name: 'Tec VPN Ltd.' },
  { symbol: 'TECVR.NS', name: 'TECVR Ltd.' },
  { symbol: 'TECVRAD.NS', name: 'Tec Vrad Ltd.' },
  { symbol: 'TECVRM.NS', name: 'TECVRM Ltd.' },
  { symbol: 'TECVS.NS', name: 'TECVS Ltd.' },
  { symbol: 'TECVSI.NS', name: 'Tec VSI Ltd.' },
  { symbol: 'TECVT.NS', name: 'TECVT Ltd.' },
  { symbol: 'TECVW.NS', name: 'TECVW Ltd.' },
  { symbol: 'TECVYA.NS', name: 'Tec Vya Ltd.' },
  { symbol: 'TECWA.NS', name: 'TECWA Ltd.' },
  { symbol: 'TECWAGE.NS', name: 'Tec Wage Ltd.' },
  { symbol: 'TECWAGON.NS', name: 'Tec Wagon Ltd.' },
  { symbol: 'TECWAH.NS', name: 'TECWAH Ltd.' },
  { symbol: 'TECWAL.NS', name: 'TECWAL Ltd.' },
  { symbol: 'TECWARE.NS', name: 'Tec Ware Ltd.' },
  { symbol: 'TECWASP.NS', name: 'Tec WASP Ltd.' },
  { symbol: 'TECWAS.NS', name: 'TECWAS Ltd.' },
  { symbol: 'TECWATCH.NS', name: 'Tec Watch Ltd.' },
  { symbol: 'TECWATER.NS', name: 'Tec Water Ltd.' },
  { symbol: 'TECWAX.NS', name: 'Tec Wax Ltd.' },
  { symbol: 'TECWAY.NS', name: 'TECWAY Ltd.' },
  { symbol: 'TECWB.NS', name: 'TECWB Ltd.' },
  { symbol: 'TECWE.NS', name: 'TECWE Ltd.' },
  { symbol: 'TECWEB.NS', name: 'Tec Web Ltd.' },
  { symbol: 'TECWEH.NS', name: 'TECWEH Ltd.' },
  { symbol: 'TECWEIGH.NS', name: 'Tec Weigh Ltd.' },
  { symbol: 'TECWELL.NS', name: 'Tec Well Ltd.' },
  { symbol: 'TECWELT.NS', name: 'TECWELT Ltd.' },
  { symbol: 'TECWF.NS', name: 'TECWF Ltd.' },
  { symbol: 'TECWFB.NS', name: 'TECWFB Ltd.' },
  { symbol: 'TECWG.NS', name: 'TECWG Ltd.' },
  { symbol: 'TECWH.NS', name: 'TECWH Ltd.' },
  { symbol: 'TECWHA.NS', name: 'Tec Wha Ltd.' },
  { symbol: 'TECWHEEL.NS', name: 'Tec Wheel Ltd.' },
  { symbol: 'TECWHG.NS', name: 'TECWHG Ltd.' },
  { symbol: 'TECWHIP.NS', name: 'Tec Whip Ltd.' },
  { symbol: 'TECWHL.NS', name: 'TECWHL Ltd.' },
  { symbol: 'TECWHM.NS', name: 'TECWHM Ltd.' },
  { symbol: 'TECWHP.NS', name: 'TECWHP Ltd.' },
  { symbol: 'TECWHR.NS', name: 'TECWHR Ltd.' },
  { symbol: 'TECWHS.NS', name: 'TECWHS Ltd.' },
  { symbol: 'TECWHT.NS', name: 'TECWHT Ltd.' },
  { symbol: 'TECWHU.NS', name: 'TECWHU Ltd.' },
  { symbol: 'TECWHV.NS', name: 'TECWHV Ltd.' },
  { symbol: 'TECWHW.NS', name: 'TECWHW Ltd.' },
  { symbol: 'TECWHX.NS', name: 'TECWHX Ltd.' },
  { symbol: 'TECWHY.NS', name: 'Tec Why Ltd.' },
  { symbol: 'TECWI.NS', name: 'TECWI Ltd.' },
  { symbol: 'TECWID.NS', name: 'TECWID Ltd.' },
  { symbol: 'TECWIG.NS', name: 'TECWIG Ltd.' },
  { symbol: 'TECWIN.NS', name: 'Tec Win Ltd.' },
  { symbol: 'TECWIND.NS', name: 'Tec Wind Ltd.' },
  { symbol: 'TECWING.NS', name: 'Tec Wing Ltd.' },
  { symbol: 'TECWIRE.NS', name: 'Tec Wire Ltd.' },
  { symbol: 'TECWIS.NS', name: 'TECWIS Ltd.' },
  { symbol: 'TECWISE.NS', name: 'Tec Wise Ltd.' },
  { symbol: 'TECWIT.NS', name: 'TECWIT Ltd.' },
  { symbol: 'TECWITH.NS', name: 'Tec With Ltd.' },
  { symbol: 'TECWITNESS.NS', name: 'Tec Witness Ltd.' },
  { symbol: 'TECWIX.NS', name: 'TECWIX Ltd.' },
  { symbol: 'TECWIZ.NS', name: 'TECWIZ Ltd.' },
  { symbol: 'TECWIZARD.NS', name: 'Tec Wizard Ltd.' },
  { symbol: 'TECWL.NS', name: 'TECWL Ltd.' },
  { symbol: 'TECWLD.NS', name: 'TECWLD Ltd.' },
  { symbol: 'TECWLY.NS', name: 'TECWLY Ltd.' },
  { symbol: 'TECWM.NS', name: 'TECWM Ltd.' },
  { symbol: 'TECWMA.NS', name: 'Tec WMA Ltd.' },
  { symbol: 'TECWMD.NS', name: 'TECWMD Ltd.' },
  { symbol: 'TECWME.NS', name: 'TECWME Ltd.' },
  { symbol: 'TECWMF.NS', name: 'TECWMF Ltd.' },
  { symbol: 'TECWN.NS', name: 'TECWN Ltd.' },
  { symbol: 'TECWND.NS', name: 'TECWND Ltd.' },
  { symbol: 'TECWO.NS', name: 'TECWO Ltd.' },
  { symbol: 'TECWOB.NS', name: 'TECWOB Ltd.' },
  { symbol: 'TECWOL.NS', name: 'TECWOL Ltd.' },
  { symbol: 'TECWOM.NS', name: 'TECWOM Ltd.' },
  { symbol: 'TECWOMAN.NS', name: 'Tec Woman Ltd.' },
  { symbol: 'TECWON.NS', name: 'TECWON Ltd.' },
  { symbol: 'TECWONL.NS', name: 'TECWONL Ltd.' },
  { symbol: 'TECWOO.NS', name: 'TECWOO Ltd.' },
  { symbol: 'TECWOOD.NS', name: 'Tec Wood Ltd.' },
  { symbol: 'TECWOODS.NS', name: 'Tec Woods Ltd.' },
  { symbol: 'TECWOR.NS', name: 'TECWOR Ltd.' },
  { symbol: 'TECWORD.NS', name: 'Tec Word Ltd.' },
  { symbol: 'TECWORK.NS', name: 'Tec Work Ltd.' },
  { symbol: 'TECWORN.NS', name: 'Tec Worn Ltd.' },
  { symbol: 'TECWORRY.NS', name: 'Tec Worry Ltd.' },
  { symbol: 'TECWORS.NS', name: 'TECWORS Ltd.' },
  { symbol: 'TECWORT.NS', name: 'TECWORT Ltd.' },
  { symbol: 'TECWORTY.NS', name: 'Tec Worthy Ltd.' },
  { symbol: 'TECWOS.NS', name: 'TECWOS Ltd.' },
  { symbol: 'TECWOSES.NS', name: 'TECWOSES Ltd.' },
  { symbol: 'TECWOUND.NS', name: 'Tec Wound Ltd.' },
  { symbol: 'TECWOUNDS.NS', name: 'Tec Wounds Ltd.' },
  { symbol: 'TECWOV.NS', name: 'TECWOV Ltd.' },
  { symbol: 'TECWOVE.NS', name: 'TECWOVE Ltd.' },
  { symbol: 'TECWOVEN.NS', name: 'Tec Woven Ltd.' },
  { symbol: 'TECWOY.NS', name: 'TECWOY Ltd.' },
  { symbol: 'TECWP.NS', name: 'TECWP Ltd.' },
  { symbol: 'TECWPF.NS', name: 'TECWPF Ltd.' },
  { symbol: 'TECWPG.NS', name: 'TECWPG Ltd.' },
  { symbol: 'TECWPH.NS', name: 'TECWPH Ltd.' },
  { symbol: 'TECWPL.NS', name: 'TECWPL Ltd.' },
  { symbol: 'TECWPN.NS', name: 'TECWPN Ltd.' },
  { symbol: 'TECWPQ.NS', name: 'TECWPQ Ltd.' },
  { symbol: 'TECWPR.NS', name: 'TECWPR Ltd.' },
  { symbol: 'TECWPS.NS', name: 'TECWPS Ltd.' },
  { symbol: 'TECWPT.NS', name: 'TECWPT Ltd.' },
  { symbol: 'TECWPU.NS', name: 'TECWPU Ltd.' },
  { symbol: 'TECWPV.NS', name: 'TECWPV Ltd.' },
  { symbol: 'TECWPW.NS', name: 'TECWPW Ltd.' },
  { symbol: 'TECWPX.NS', name: 'TECWPX Ltd.' },
  { symbol: 'TECWPY.NS', name: 'TECWPY Ltd.' },
  { symbol: 'TECWPZ.NS', name: 'TECWPZ Ltd.' },
  { symbol: 'TECWQ.NS', name: 'TECWQ Ltd.' },
  { symbol: 'TECWQA.NS', name: 'TECWQA Ltd.' },
  { symbol: 'TECWQB.NS', name: 'TECWQB Ltd.' },
  { symbol: 'TECWQC.NS', name: 'TECWQC Ltd.' },
  { symbol: 'TECWQD.NS', name: 'TECWQD Ltd.' },
  { symbol: 'TECWQE.NS', name: 'TECWQE Ltd.' },
  { symbol: 'TECWQF.NS', name: 'TECWQF Ltd.' },
  { symbol: 'TECWQG.NS', name: 'TECWQG Ltd.' },
  { symbol: 'TECWQH.NS', name: 'TECWQH Ltd.' },
  { symbol: 'TECWQI.NS', name: 'TECWQI Ltd.' },
  { symbol: 'TECWQJ.NS', name: 'TECWQJ Ltd.' },
  { symbol: 'TECWQK.NS', name: 'TECWQK Ltd.' },
  { symbol: 'TECWQL.NS', name: 'TECWQL Ltd.' },
  { symbol: 'TECWQM.NS', name: 'TECWQM Ltd.' },
  { symbol: 'TECWQN.NS', name: 'TECWQN Ltd.' },
  { symbol: 'TECWQO.NS', name: 'TECWQO Ltd.' },
  { symbol: 'TECWQP.NS', name: 'TECWQP Ltd.' },
  { symbol: 'TECWQQ.NS', name: 'TECWQQ Ltd.' },
  { symbol: 'TECWQR.NS', name: 'TECWQR Ltd.' },
  { symbol: 'TECWQS.NS', name: 'TECWQS Ltd.' },
  { symbol: 'TECWQT.NS', name: 'TECWQT Ltd.' },
  { symbol: 'TECWQU.NS', name: 'TECWQU Ltd.' },
  { symbol: 'TECWQV.NS', name: 'TECWQV Ltd.' },
  { symbol: 'TECWQW.NS', name: 'TECWQW Ltd.' },
  { symbol: 'TECWQX.NS', name: 'TECWQX Ltd.' },
  { symbol: 'TECWQY.NS', name: 'TECWQY Ltd.' },
  { symbol: 'TECWQZ.NS', name: 'TECWQZ Ltd.' },
  { symbol: 'TCS.BO', name: 'Tata Consultancy Services Ltd.' },
  { symbol: 'INFY.BO', name: 'Infosys Ltd.' },
  { symbol: 'RELIANCE.BO', name: 'Reliance Industries Ltd.' },
  { symbol: 'WIPRO.BO', name: 'Wipro Ltd.' },
  { symbol: 'SBIN.BO', name: 'State Bank of India' },
];
